name: Pruebas Unitarias

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    name: Ejecutar pruebas unitarias
    runs-on: ubuntu-latest
    
    steps:
    - name: Obtener código
      uses: actions/checkout@v4
    
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Instalar dependencias
      run: npm ci
    
    - name: Ejecutar pruebas unitarias
      run: npm run test:coverage
    
    - name: Subir informe de cobertura de código
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
